# Builds and publishes the documentation website to gh-pages branch
name: Build docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          submodules: true

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.x

      - name: Install DocLinkChecker
        run: dotnet tool install DocLinkChecker

      # Check for missing / broken links in the *.md files prior to building the website
      - name: Check Documentation Links
        run: .\docfx-utils.ps1 -d

      - name: Setup DocFX
        run: dotnet tool restore

      - name: Setup Bonsai
        working-directory: .bonsai
        run: .\Setup.ps1

      - name: Build Documentation
        run: .\docfx-utils.ps1 -b

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: _site
          if-no-files-found: error

  check:
    name: Check Links
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: _site
          path: _site
      
      # This checks for missing / broken links in the *.html files after building the website.
      # We need to run this step here to check that all auto-generated API pages have valid links too.
      - name: Check HTML Links After Building
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: --verbose --no-progress --base _site --exclude ^https://github\.com.*merge.* --exclude ^https://github\.com.*apiSpec.* '_site/**/*.html'
          fail: true

  deploy:
    name: Deploy docs to gh-pages
    runs-on: ubuntu-latest
    needs: [ build, check ]
    if: github.event_name == 'push'
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: _site
          path: _site
      
      - name: Checkout gh-pages
        uses: actions/checkout@v4.1.1
        with:
          ref: gh-pages
          path: gh-pages

      - name: Publish to github pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          force_orphan: true

